### ISSUE TITLE
"Freifunk" Popup

### ISSUE THREAD

**Issue by flopp** [flopp/FloppsTolleKarte#40]
Button "FF uci". Next click on map shows a popup with the following, selectable text:

    uci set gluon-node-info.@location[0]=’location’
    uci set gluon-node-info.@location[0].share_location=’1′
    uci set gluon-node-info.@location[0].latitude=’51.194653′
    uci set gluon-node-info.@location[0].longitude=’6.431345′
    uci commit

where the latitude and longitude fields correspond to the click position.

**Comment by Adorfer** [comment]
Following the discussion at 
https://github.com/ffnord/meshviewer/pull/13#issuecomment-165869547

i would suggest to have additionally a mode to start the map "in freifunk mode". 
in other works: Not offering geocaches from opencaching. 
(or in extreme form: harvesting data from http://www.freifunk-karte.de ;-)

**Comment by flopp** [comment]
'freifunk mode' (e.g. no geocaches) can be enabled by adding the 'feature parameter' `f=` (no additional layers are shown) to the URL. 
See #50 for details.

I have also set the default mode to *not* show geocaches.

**Comment by Adorfer** [comment]
Great!
@Plumpudding

**Comment by flopp** [comment]
@Adorfer is the "FF uci" button still needed (as specified in https://github.com/flopp/FloppsTolleKarte/issues/40#issue-75737557)?

**Comment by plumpudding** [comment]
Yes, it's still very useful.

**Comment by flopp** [comment]
afdd00bf508b77ec879fe4b8f2e0ae4a43885458

- added "Freifunk" mode to the sidebar (which can be activated using the URL feature flag 'f', i.e. http:/www.flopp.net/?f=f
- added button "Show Freifunk info un next click" which displays a popup with the above uci commands
