### ISSUE TITLE
cache baloon on map is not translated

### ISSUE THREAD

**Issue by andrixnet** [flopp/FloppsTolleKarte#49]
On the map, for geocaches, the baloon popup contains english text: 
```
OR0078 [LALEA3] Baza de agrement Trivale
by andrixnet
Traditional (small)
difficulty: 2/5 terrain: 1.5/5
#finds: 0
```

Map layer buttons and their popup description is also english only.

Sections "games" and "maps" for external services should also be translatable.

Should the text "Angaben gemäß § 5 TMG, Verantwortlich für den Inhalt nach § 55 Abs. 2 RStV:" be translated to all languages? (section INFO)

**Comment by flopp** [comment]
8c1c701: added translations to cache popup
