### ISSUE TITLE
Toogle 'features' via URL parameter

### ISSUE THREAD

**Issue by flopp** [flopp/FloppsTolleKarte#50]
The features/additional layers 'administrative boundaries', 'hillshading', 'nature protection areas', and 'geocaches' shall be toggleable via an URL parameter

**Comment by flopp** [comment]
b1e053eae05b04c2e2033da6bdd46ac7c8d84e58

Added URL parameter `f=...` to toggle features; extended permalink generator to set the feature parameter to the current configuration.

If there is no feature parameter in the URL, features are toggled as stored in the cookies.
If there is a feature parameter `f=$FEATURESTRING`,
- administrative boundaries are enabled if `$FEASTURESTRING` contains `b` or `B``
- geocaches are enabled if `$FEASTURESTRING` contains `g` or `G`
- hillshading is enabled if `$FEASTURESTRING` contains `h` or `H`
- nature protection areas are enabled if `$FEASTURESTRING` contains `n` or `N`

Example: the URL `flopp.net/?f=hg` shows a map with hillshading and geocaches.

**Comment by andrixnet** [comment]
It would also help to include display language in URL, so that the site can be called up directly into that language. 
Thank you.

**Comment by flopp** [comment]
@andrixnet I have created issue #52 addressing your feature request.
