### ISSUE TITLE
Reference geocache and show with baloon from URL

### ISSUE THREAD

**Issue by andrixnet** [flopp/FloppsTolleKarte#57]
This is a feature request. 

I would like to call the map referencing a geocache in the URL.
The map should open centered on that geocache, geocaches be enabled (actually by f=g) and the geocache balloon info be shown (as when user clicks on that geocache).

Some modifications I propose to OPENCACHING-PL here https://github.com/opencaching/opencaching-pl/pull/454 could make good use of such a feature.

Thank you.

**Comment by flopp** [comment]
Nice idea!

**Comment by flopp** [comment]
dfc5312234042d238a26550bce3dab75707d0628

- added new URL parameter 'g=CACHECODE'
- CACHECODE may be any cache code from OC.de, OC.pl, OC.nl, OC.ro, OC.us, OC.org.uk (e.g. OCF90E)
- if the parameter is given, (1) the 'geocaching mode' is automatically activated in the sidebar,  (2) the map is centered on the given geocache, (3) a popup with the cache infos is shown (as if the cache marker has been clicked)

**Comment by andrixnet** [comment]
Great. Thank you. 
I am updating our code as well. 

Note: the g= parameter is not included with the "Create Permalink" button

**Comment by flopp** [comment]
Would you expect the permalink to have a "g=" parameter, if it was created while a geocache popup was open?

**Comment by andrixnet** [comment]
Yes, if the project's aim towards the user is to do 100% of the following: 
1. save and restore the exact view between browser sessions
2. ability to share exact view with others

**Comment by flopp** [comment]
Yes, that's the aim.
