### ISSUE TITLE
Google map terms of service violation

### ISSUE THREAD

**Issue by andrixnet** [flopp/FloppsTolleKarte#62]
Received by ocpl mailing list: 

> 
> Hi Piotr,
> 
> The changes you made currently are fine. Also, please update the Flopp's map(Screenshot attached), which is in Branding violation.
> 
> Regards,
> Google Maps Team

**Comment by andrixnet** [comment]
On opencaching-pl the problems were: 

- [ ] streetmap icon and functionality being active for other map sources then Google's
- [ ] Google logo being visible (lower left) for other map sources then Google's map
- [ ] search by address using Google API when showing other map sources

**Comment by flopp** [comment]
Thanks for forwarding this info to me.

I think I will completely disable the map until I have found a solution for the issue.

**Comment by andrixnet** [comment]
Take a look from here https://github.com/opencaching/opencaching-pl/issues/665 how opencaching-pl solved the problems, hope it helps.

**Comment by flopp** [comment]
3ff6d81

- removed google logo on non-google maps
- removed streetview control on all maps
- completely replaces google's geocoder by osm's nominatim search
